// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufejkvmpebsfmiswyqcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZWprdm1wZWJzZm1pc3d5cWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjAxNjgsImV4cCI6MjA2NzM5NjE2OH0.2EG7zMfVfkq9v4Gp2kQeo_pXFuO021bsw_W6nHUttnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});